<div class="form-group">
 <select class="form-control" id="locationBox">
    <option selected>--Pilih kawasan--</option>
   <optgroup label="Johor">
     <option value="JHR01">Pulau Aur</option>
     <option value="JHR01">Pemanggil</option>
     <option value="JHR02">Kota Tinggi</option>
     <option value="JHR02">Mersing</option>
     <option value="JHR02">Johor Bahru</option>
     <option value="JHR03">Kluang</option>
     <option value="JHR03">Pontian</option>
     <option value="JHR04">Batu Pahat</option>
     <option value="JHR04">Muar</option>
     <option value="JHR04">Segamat</option>
     <option value="JHR04">Gemas</option>
 </optgroup>
 <optgroup label="Kedah">
   <option value="KDH01">Kota Setar</option>
   <option value="KDH01">Kubang Pasu</option>
   <option value="KDH01">Pokok Sena</option>
   <option value="KDH02">Pendang</option>
   <option value="KDH02">Kuala Muda</option>
   <option value="KDH02">Yan</option>
   <option value="KDH03">Padang Terap</option>
   <option value="KDH03">Sik</option>
   <option value="KDH04">Baling</option>
   <option value="KDH05">Kulim</option>
   <option value="KDH05">Bandar Bahru</option>
   <option value="KDH06">Langkawi</option>
   <option value="KDH07">Gunung Jerai</option>
</optgroup>
<optgroup label="Kelantan">
 <option value="KTN01">Kota Bahru</option>
 <option value="KTN01">Bachok</option>
 <option value="KTN01">Pasir Puteh</option>
 <option value="KTN01">Tumpat</option>
 <option value="KTN01">Pasir Mas</option>
 <option value="KTN01">Tanah Merah</option>
 <option value="KTN01">Machang</option>
 <option value="KTN01">Kuala Krai</option>
 <option value="KTN01">Mukim Chiku</option>
 <option value="KTN03">Jeli</option>
 <option value="KTN03">Gua Musang</option>
 <option value="KTN03">Mukim Galas</option>
 <option value="KTN03">Bertam</option>
</optgroup>
<optgroup label="Melaka">
<option value="MLK01">Bandar Melaka</option>
<option value="MLK01">Alor Gajah</option>
<option value="MLK01">Jasin</option>
<option value="MLK01">Masjid Tanah</option>
<option value="MLK01">Merlimau</option>
<option value="MLK01">Nyalas</option>
</optgroup>
<optgroup label="Negeri Sembilan">
<option value="NGS01">Jempol</option>
<option value="NGS01">Tampin</option>
<option value="NGS02">Port Dickson</option>
<option value="NGS02">Seremban</option>
<option value="NGS02">Jelebu</option>
<option value="NGS02">Rembau</option>
</optgroup>
<optgroup label="Pahang">
<option value="PHG01">Pulau Tioman</option>
<option value="PHG02">Kuantan</option>
<option value="PHG02">Pekan</option>
<option value="PHG02">Rompin</option>
<option value="PHG02">Muadzam Shah</option>
<option value="PHG03">Maran</option>
<option value="PHG03">Chenor</option>
<option value="PHG03">Temerloh</option>
<option value="PHG03">Bera</option>
<option value="PHG03">Jerantut</option>
<option value="PHG04">Bentong</option>
<option value="PHG04">Raub</option>
<option value="PHG04">Kuala Lipis</option>
<option value="PHG05">Genting Sempah</option>
<option value="PHG05">Janda Baik</option>
<option value="PHG05">Bukit Tinggi</option>
<option value="PHG06">Bukit Fraser</option>
<option value="PHG06">Genting Highlands</option>
<option value="PHG06">Cameron Highlands</option>
</optgroup>
<optgroup label="Perak">
<option value="PRK01">Tapah</option>
<option value="PRK01">Slim River</option>
<option value="PRK01">Tanjung Malim</option>
<option value="PRK02">Ipoh</option>
<option value="PRK02">Batu Gajah</option>
<option value="PRK02">Kampar</option>
<option value="PRK02">Sungai Siput</option>
<option value="PRK02">Kuala Kangsar</option>
<option value="PRK03">Pengkalan Hulu</option>
<option value="PRK03">Grid</option>
<option value="PRK03">Lenggong</option>
<option value="PRK04">Temenggung</option>
<option value="PRK04">Belum</option>
<option value="PRK05">Teluk Intan</option>
<option value="PRK05">Bagan Datoh</option>
<option value="PRK05">Kampung Gajah</option>
<option value="PRK05">Sri Iskandar</option>
<option value="PRK05">Beruas</option>
<option value="PRK05">Parit</option>
<option value="PRK05">Lumut</option>
<option value="PRK05">Setiawan</option>
<option value="PRK05">Pulau Pangkor</option>
<option value="PRK06">Selama</option>
<option value="PRK06">Taiping</option>
<option value="PRK06">Bagan Serai</option>
<option value="PRK06">Parit Buntar</option>
<option value="PRK07">Bukit Larut</option>
</optgroup>
<optgroup label="Perlis">
<option value="PLS01">Kangar</option>
<option value="PLS01">Padang Besar</option>
<option value="PLS01">Arau</option>
</optgroup>
<optgroup label="Pulau Pinang">
<option value="PNG01">Pulau Pinang</option>
</optgroup>
<optgroup label="Sabah">
<option value="SBH01">Sandakan</option>
<option value="SBH01">Bandar Bukir Garam</option>
<option value="SBH01">Semawang</option>
<option value="SBH01">Temanggong</option>
<option value="SBH01">Tambisan</option>
<option value="SBH02">Pinangah</option>
<option value="SBH02">Terusan</option>
<option value="SBH02">Beluran</option>
<option value="SBH02">Kuamut</option>
<option value="SBH02">Telupit</option>
<option value="SBH03">Lahad Datu</option>
<option value="SBH03">Kunak</option>
<option value="SBH03">Silabukan</option>
<option value="SBH03">Tungku</option>
<option value="SBH03">Sahabat</option>
<option value="SBH03">Semporna</option>
<option value="SBH04">Tawau</option>
<option value="SBH04">Balong</option>
<option value="SBH04">Merotai</option>
<option value="SBH04">Kalabakan</option>
<option value="SBH05">Kudat</option>
<option value="SBH05">Kota Marudu</option>
<option value="SBH05">Pitas</option>
<option value="SBH05">Pulau Banggi</option>
<option value="SBH06">Gunung Kinabalu</option>
<option value="SBH07">Papar</option>
<option value="SBH07">Ranau</option>
<option value="SBH07">Kota Belud</option>
<option value="SBH07">Tuaran</option>
<option value="SBH07">Penampang</option>
<option value="SBH07">Kota Kinabalu</option>
<option value="SBH08">Pensiangan</option>
<option value="SBH08">Keningau</option>
<option value="SBH08">Tambunan</option>
<option value="SBH08">Nabawan</option>
<option value="SBH09">Sipitang</option>
<option value="SBH09">Membakut</option>
<option value="SBH09">Beaufort</option>
<option value="SBH09">Kuala Penyu</option>
<option value="SBH09">Weston</option>
<option value="SBH09">Tenom</option>
<option value="SBH09">Long Pa Sia</option>
</optgroup>
<optgroup label="Sarawak">
<option value="SWK01">Limbang</option>
<option value="SWK01">Sundar</option>
<option value="SWK01">Terusan</option>
<option value="SWK01">Lawas</option>
<option value="SWK02">Niah</option>
<option value="SWK02">Belaga</option>
<option value="SWK02">Sibuti</option>
<option value="SWK02">Miri</option>
<option value="SWK02">Bekenu</option>
<option value="SWK02">Marudi</option>
<option value="SWK03">Song</option>
<option value="SWK03">Bilingan</option>
<option value="SWK03">Sebauh</option>
<option value="SWK03">Bintulu</option>
<option value="SWK03">Tatau</option>
<option value="SWK03">Kapit</option>
<option value="SWK04">Igan</option>
<option value="SWK04">Kanowit</option>
<option value="SWK04">Sibu</option>
<option value="SWK04">Dalat</option>
<option value="SWK04">Oya</option>
<option value="SWK05">Belawai</option>
<option value="SWK05">Matu</option>
<option value="SWK05">Daro</option>
<option value="SWK05">Sarikei</option>
<option value="SWK05">Julau</option>
<option value="SWK05">Bitangor</option>
<option value="SWK05">Rajang</option>
<option value="SWK06">Kabong</option>
<option value="SWK06">Lingga</option>
<option value="SWK06">Sri Aman</option>
<option value="SWK06">Engkelili</option>
<option value="SWK06">Betong</option>
<option value="SWK06">Spaoh</option>
<option value="SWK06">Pusa</option>
<option value="SWK06">Saratok</option>
<option value="SWK06">Roban</option>
<option value="SWK06">Debak</option>
<option value="SWK07">Samarahan</option>
<option value="SWK07">Simunjan</option>
<option value="SWK07">Serian</option>
<option value="SWK07">Sebuyau</option>
<option value="SWK07">Meludam</option>
<option value="SWK08">Kuching</option>
<option value="SWK08">Bau</option>
<option value="SWK08">Lundu</option>
<option value="SWK08">Sematan</option>
<option value="SWK09">Zon Khas</option>
</optgroup>
<optgroup label="Selangor">
<option value="SGR01">Gombak</option>
<option value="SGR01">Hulu Selangor</option>
<option value="SGR01">Rawang</option>
<option value="SGR01">Hulu Langat</option>
<option value="SGR01">Sepang</option>
<option value="SGR01">Petaling</option>
<option value="SGR01">Shah Alam</option>
<option value="SGR02">Sabak Bernam</option>
<option value="SWK02">Kuala Selangor</option>
<option value="SWK02">Klang</option>
<option value="SWK03">Kuala Langat</option>
</optgroup>
<optgroup label="Terengganu">
<option value="TRG01">Kuala Terengganu</option>
<option value="TRG01">Marang</option>
<option value="TRG02">Besut</option>
<option value="TRG02">Setiu</option>
<option value="TRG03">Hulu Terengganu</option>
<option value="TRG04">Kemaman</option>
<option value="TRG04">Dungun</option>
</optgroup>
<optgroup label="Putrajaya">
<option value="SGR04">Putrajaya</option>
</optgroup>
<optgroup label="Kuala Lumpur">
<option value="SGR03">Kuala Lumpur</option>
</optgroup>
<optgroup label="Labuan">
<option value="WLY02">Labuan</option>
</optgroup>

 </select>
</div>
